version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - /Users/rohaizan/Codes/microk8s/emasjid/cdn.e-masjid.my/nginx/img-init:/usr/share/nginx/html

  image-store-api:
    build:
      context: ./api/image-store-api
    ports:
      - "9000:8080"
    environment:
      - GO_ENV=dev
    depends_on:
      - nginx
    volumes:
      - /Users/rohaizan/Codes/microk8s/emasjid/cdn.e-masjid.my/nginx/img-init:/app2
    command: ["./image-server"]

