version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/img-init:/usr/share/nginx/html

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cdn_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      
  cdn-api:
    build:
      context: ./api/cdn-api
    ports:
      - "9000:8080"
    environment:
      - GO_ENV=dev
    depends_on:
      - nginx
    volumes:
      - ./nginx/img-init:/app2
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./cdn-api"]

